### ISSUE TITLE
Failed error to publish

### ISSUE THREAD

**Issue by jcmoral90** [reorx/obsidian-telegraph-publish#1]
![image](https://user-images.githubusercontent.com/64127850/159141199-a24cfe3b-08ba-4c8d-ae55-7a5e1a60b031.png)

**Comment by reorx** [comment]
Interesting, this error probably means the plugin did not get the HTML rendered by preview mode, can you provide a list of plugins that you installed?

**Comment by mishozghuladze** [comment]
Hey, the same here: 
![image](https://user-images.githubusercontent.com/77275677/159179727-76c9212b-8687-43cd-a4bf-8d4f0f11fd28.png)

Here's the list of my plugins:
![image](https://user-images.githubusercontent.com/77275677/159179742-881f9375-680c-4f14-a8b1-c0bf976c69b6.png)

**Comment by reorx** [comment]
Turns out it's indeed caused by a plugin, but it's one of mine, not yours, led me to use the wrong way to get the HTML of preview content. I've fixed this problem in release 1.1.1, please update and try again.

**Comment by mishozghuladze** [comment]
![image](https://user-images.githubusercontent.com/77275677/159229676-f58fb3ee-cb89-4a4c-9c65-8db818a89741.png)

Thanks! it works now.

**Comment by reorx** [comment]
In case anyone still gets this error for edge cases, I added a new setting called `HTML Source` in [release 1.2.0](https://github.com/reorx/obsidian-telegraph-publish/releases/tag/1.2.0),
try to use `MarkdownRenderer` if you get into trouble.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/405972/159286919-334f7928-1556-41af-af72-96e82c17eb54.png">

**Comment by jcmoral90** [comment]
It works fine, but when I post my note on Facebook it is impossible, is this due to Russian app censorship policies?
