### ISSUE TITLE
not all of the note content is published

### ISSUE THREAD

**Issue by barnabaslabs** [reorx/obsidian-telegraph-publish#2]
Hi! I love the idea of this to quickly share a page. I’ve got it working - sort of. When I set the HTML Source to “MarkdownRenderer” nothing happens when I try to publish or update. When it is left on the default of “Preview” it works to publish and update the post, but it doesn’t publish the whole post. I’ve tried on several notes, but they seem to get cut off after 300-400 words. For example: [Luke Reading Guide – Telegraph](https://telegra.ph/Luke-Reading-Guide-03-21) This note should have a header and content for every chapter in Luke (24 of them), but the published note only shows down to 8. Any ideas on what is going on? Thanks!

**Comment by reorx** [comment]
Hi! Thanks for reporting, I've investigated the problem and found out that using "Preview" as HTML Source is fundamentally defective, so I dropped this setting and make "MarkdownRenderer" the default and unchangeable option for HTML Source.

The reason "Preview" did not work is that Obsidian uses a progressive rendering mechanism in preview mode,
while scrolling, only the visible part with a small margin is rendered to DOM elements,
this makes it impossible to get full HTML content for long documents.

I've tested the publishing for long documents based on your article, see the result here: https://telegra.ph/Test-Luke-Reading-Guide-4-04-04

> When I set the HTML Source to “MarkdownRenderer” nothing happens when I try to publish or update

I cannot reproduce it and didn't have a clue about this, but you can try again with the new version [1.2.2](https://github.com/reorx/obsidian-telegraph-publish/releases/tag/1.2.2), if this still happens, please tell me. Screenshots of the Developer Tools and your plugin list would be helpful for debugging.

**Comment by barnabaslabs** [comment]
Thanks for your work on this. I tested out the update and now it works as expected! I don't know what else changed, but I am running the insider builds and use numerous plugins. If the problem shows up again, I'll share more details.
