### ISSUE TITLE
publishing fail

### ISSUE THREAD

**Issue by barnabaslabs** [reorx/obsidian-telegraph-publish#3]
![image](https://user-images.githubusercontent.com/121033/168684351-8a59276b-e68a-4a82-9876-31e0e3b26be7.png)

This is the note I'm trying to publish when I encountered the error: https://gist.github.com/pastorjack/bcc03c6573579fa2e7c49455a2003d9e

**Comment by reorx** [comment]
Hi pastorjack, I just fixed this bug in release [1.2.3](https://github.com/reorx/obsidian-telegraph-publish/releases/tag/1.2.3), please update and retry.

**Comment by barnabaslabs** [comment]
Thanks, it works as expected now!!!
